# Generated by Django 3.1.6 on 2021-02-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
